title:   <h1 style="font-size: 42px;">VICTOR S. DIPEOLU</h1>
logo: https://github.com/Vicmandip1/Portfolio/blob/main/Picture1.jpg?raw=true
#show_downloads: true
google_analytics: 1.6
theme: jekyll-theme-minimal


contact:
  email: dipeoluvictors@gmail.com
  phone: +1 (647) 668-1292
  linkedin: www.linkedin.com/in/victor-dipeolu-685893267
